category: 'human_nerf'


##############################################3
## Network Specs

non_rigid_motion_mlp:
  kick_in_iter: 10000
  full_band_iter: 50000

pose_decoder:
  kick_in_iter: 20000

##############################################3
## Data Configuration

train_keyfilter: ['rays',
                  'motion_bases', 'motion_weights_priors',
                  'cnl_bbox', 'dst_posevec_69']
test_keyfilter: ['rays', 'target_rgbs', 
                 'motion_bases', 'motion_weights_priors',
                  'cnl_bbox', 'dst_posevec_69']

train:
  perturb: 1.        # only for training, set to 0. for no jitter, 1. for jitter
  batch_size: 1
  shuffle: True
  drop_last: False
  maxiter: 200000
  lr: 0.0005  # 5e-4
  lr_mweight_vol_decoder: 0.00005 # 5e-5
  lr_pose_decoder: 0.00005        # 5e-5
  lr_non_rigid_mlp: 0.00005       # 5e-5
  lrate_decay: 500
  optimizer: 'adam'
  log_interval: 20
  save_checkpt_interval: 2000
  save_model_interval: 50000
  ray_shoot_mode: 'patch'
  lossweights:
    lpips: 1.0
    mse: 0.2


progress:
  batch_size: 1
  shuffle: False
  drop_last: False
  dump_interval: 5000

movement:
  batch_size: 1
  shuffle: False
  drop_last: False

freeview:
  batch_size: 1
  shuffle: False
  drop_last: False
  frame_idx: 0

tpose:
  batch_size: 1
  shuffle: False
  drop_last: False


##############################################3
## Misc

sex: 'neutral'
total_bones: 24
bbox_offset: 0.3

load_net: latest
save_all: True    # save all checkpoints

patch:
  sample_subject_ratio: 0.8
  N_patches: 6
  size: 32      # [Patch] size of patch

N_samples: 128      # number of samples for each ray in coarse ray matching

perturb: 1.        # only for training, set to 0. for no jitter, 1. for jitter

primary_gpus: [0]
netchunk_per_gpu: 300000 # number of pts sent through network in parallel, decrease if running out of memory
chunk: 32768   # 32768=1024*32, number of rays processed in parallel, decrease if running out of memory
n_gpus: 1

show_alpha: False  
show_truth: False
