task: 'wild'
experiment: 'single_gpu'

load_net: latest

##############################################3
## Network Specs

# non-rigid motion mlp
non_rigid_motion_mlp:
  kick_in_iter: 100000
  full_band_iter: 200000

# pose decoder
pose_decoder:
  kick_in_iter: 20000

##############################################3
## Data Configuration


bgcolor: [255., 255., 255.]
resize_img_scale: 0.5

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
